import type { Bike, Review, Rental, User, Category } from "./types"

export const mockUsers: User[] = [
  {
    id: "1",
    name: "John Owner",
    email: "owner@example.com",
    role: "owner",
    rating: 4.8,
    totalRentals: 0,
    avatar: "/bike-owner-avatar.jpg",
  },
  {
    id: "2",
    name: "Sarah Renter",
    email: "renter@example.com",
    role: "renter",
    rating: 4.5,
    totalRentals: 12,
    avatar: "/bike-renter-avatar.jpg",
  },
  {
    id: "admin",
    name: "Super Admin",
    email: "admin@hirebellbreaks.com",
    role: "admin",
    rating: 5,
    totalRentals: 0,
    avatar: "/admin-avatar.jpg",
    verified: true,
  },
]

export const mockBikes: Bike[] = [
  {
    id: "1",
    ownerId: "1",
    name: "Mountain Explorer Pro",
    description: "High-performance mountain bike perfect for trails",
    price: 25,
    rating: 4.7,
    likes: 24,
    images: ["/mountain-bike-red.jpg", "/mountain-bike-side-view.jpg"],
    location: {
      lat: 40.7128,
      lng: -74.006,
      address: "123 Bike Lane, New York, NY",
    },
    available: true,
    category: "Mountain",
    totalRentals: 15,
    condition: "Excellent",
    dateAdded: "2024-01-10",
  },
  {
    id: "2",
    ownerId: "1",
    name: "City Cruiser Deluxe",
    description: "Comfortable city bike for urban adventures",
    price: 15,
    rating: 4.5,
    likes: 18,
    images: ["/city-bike-blue.jpg", "/city-bike-basket.jpg"],
    location: {
      lat: 40.758,
      lng: -73.9855,
      address: "456 Urban Ave, New York, NY",
    },
    available: true,
    category: "City",
    totalRentals: 23,
    condition: "Good",
    dateAdded: "2024-01-05",
  },
  {
    id: "3",
    ownerId: "1",
    name: "Road Racer Elite",
    description: "Lightweight road bike for speed enthusiasts",
    price: 30,
    rating: 4.9,
    likes: 32,
    images: ["/road-bike-black.jpg", "/road-bike-race.png"],
    location: {
      lat: 40.7489,
      lng: -73.968,
      address: "789 Speed St, New York, NY",
    },
    available: false,
    category: "Road",
    totalRentals: 8,
    condition: "Excellent",
    dateAdded: "2024-01-15",
  },
  {
    id: "4",
    ownerId: "1",
    name: "Electric Commuter",
    description: "E-bike perfect for daily commutes with pedal assist",
    price: 35,
    rating: 4.8,
    likes: 28,
    images: ["/electric-bike.jpg"],
    location: {
      lat: 40.7505,
      lng: -73.9934,
      address: "234 Electric Ave, New York, NY",
    },
    available: true,
    category: "Electric",
    totalRentals: 19,
    condition: "Excellent",
    dateAdded: "2024-01-20",
  },
  {
    id: "5",
    ownerId: "1",
    name: "Vintage Classic",
    description: "Retro-style bike with modern components",
    price: 20,
    rating: 4.6,
    likes: 15,
    images: ["/vintage-bike.jpg"],
    location: {
      lat: 40.758,
      lng: -73.9855,
      address: "567 Retro Road, New York, NY",
    },
    available: true,
    category: "City",
    totalRentals: 12,
    condition: "Good",
    dateAdded: "2024-01-12",
  },
  {
    id: "6",
    ownerId: "1",
    name: "BMX Stunt Pro",
    description: "Durable BMX bike for tricks and stunts",
    price: 18,
    rating: 4.4,
    likes: 21,
    images: ["/bmx-bike.jpg"],
    location: {
      lat: 40.7614,
      lng: -73.9776,
      address: "890 Stunt St, New York, NY",
    },
    available: true,
    category: "BMX",
    totalRentals: 9,
    condition: "Fair",
    dateAdded: "2024-01-08",
  },
  {
    id: "7",
    ownerId: "1",
    name: "Hybrid Comfort",
    description: "Versatile hybrid bike for city and light trails",
    price: 22,
    rating: 4.7,
    likes: 26,
    images: ["/hybrid-bike.jpg"],
    location: {
      lat: 40.745,
      lng: -73.99,
      address: "345 Hybrid Way, New York, NY",
    },
    available: true,
    category: "Hybrid",
    totalRentals: 17,
    condition: "Excellent",
    dateAdded: "2024-01-18",
  },
  {
    id: "8",
    ownerId: "1",
    name: "Folding Compact",
    description: "Space-saving folding bike perfect for storage",
    price: 16,
    rating: 4.3,
    likes: 14,
    images: ["/folding-bike.jpg"],
    location: {
      lat: 40.752,
      lng: -73.975,
      address: "678 Compact Ct, New York, NY",
    },
    available: true,
    category: "Folding",
    totalRentals: 11,
    condition: "Good",
    dateAdded: "2024-01-14",
  },
  {
    id: "9",
    ownerId: "1",
    name: "Cargo Hauler",
    description: "Heavy-duty cargo bike for transporting goods",
    price: 28,
    rating: 4.6,
    likes: 19,
    images: ["/cargo-bike.jpg"],
    location: {
      lat: 40.74,
      lng: -73.995,
      address: "901 Cargo Ln, New York, NY",
    },
    available: true,
    category: "Cargo",
    totalRentals: 14,
    condition: "Good",
    dateAdded: "2024-01-16",
  },
  {
    id: "10",
    ownerId: "1",
    name: "Kids Adventure",
    description: "Safe and fun bike designed for children",
    price: 12,
    rating: 4.8,
    likes: 22,
    images: ["/kids-bike.jpg"],
    location: {
      lat: 40.756,
      lng: -73.982,
      address: "123 Kids Corner, New York, NY",
    },
    available: true,
    category: "Kids",
    totalRentals: 20,
    condition: "Excellent",
    dateAdded: "2024-01-22",
  },
]

export const mockReviews: Review[] = [
  {
    id: "1",
    bikeId: "1",
    userId: "2",
    userName: "Sarah Renter",
    rating: 5,
    comment: "Amazing bike! Perfect for mountain trails.",
    date: "2024-01-15",
  },
  {
    id: "2",
    bikeId: "1",
    userId: "3",
    userName: "Mike Johnson",
    rating: 4,
    comment: "Great condition, would rent again.",
    date: "2024-01-10",
  },
  {
    id: "3",
    bikeId: "2",
    userId: "2",
    userName: "Sarah Renter",
    rating: 5,
    comment: "Super comfortable for city rides!",
    date: "2024-01-20",
  },
]

export const mockRentals: Rental[] = [
  {
    id: "1",
    bikeId: "3",
    bikeName: "Road Racer Elite",
    renterId: "2",
    renterName: "Sarah Renter",
    ownerId: "1",
    startDate: "2024-01-25",
    endDate: "2024-01-27",
    status: "active",
    totalPrice: 60,
  },
  {
    id: "2",
    bikeId: "1",
    bikeName: "Mountain Explorer Pro",
    renterId: "2",
    renterName: "Sarah Renter",
    ownerId: "1",
    startDate: "2024-01-15",
    endDate: "2024-01-17",
    status: "completed",
    totalPrice: 50,
  },
]

export const mockCategories: Category[] = [
  { id: "1", name: "Mountain", description: "Off-road and trail bikes", icon: "🏔️" },
  { id: "2", name: "City", description: "Urban commuting bikes", icon: "🏙️" },
  { id: "3", name: "Road", description: "Speed and racing bikes", icon: "🏁" },
  { id: "4", name: "Electric", description: "E-bikes with pedal assist", icon: "⚡" },
  { id: "5", name: "BMX", description: "Stunt and trick bikes", icon: "🎪" },
  { id: "6", name: "Hybrid", description: "Versatile all-purpose bikes", icon: "🔄" },
  { id: "7", name: "Folding", description: "Compact portable bikes", icon: "📦" },
  { id: "8", name: "Cargo", description: "Heavy-duty transport bikes", icon: "📦" },
  { id: "9", name: "Kids", description: "Children's bikes", icon: "👶" },
]
